if (FAISS_WITH_MACA)
  set(EXTRA_COMMON_COMPILE_OPTIONS_FOR_MACA
    -DFAISS_WITH_MACA
    -fPIC
  )
  set(EXTRA_CXX_COMPILE_OPTIONS_FOR_MACA ${EXTRA_COMMON_COMPILE_OPTIONS_FOR_MACA})
  set(EXTRA_CUDA_COMPILE_OPTIONS_FOR_MACA -xmaca ${EXTRA_COMMON_COMPILE_OPTIONS_FOR_MACA})
else (FAISS_WITH_MACA)
  set(EXTRA_CXX_COMPILE_OPTIONS_FOR_MAC)
  set(EXTRA_CUDA_COMPILE_OPTIONS_FOR_MACA)
endif (FAISS_WITH_MACA)